version: '3'
services:
    dynamodb:
        image: amazon/dynamodb-local
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
        volumes:
            - dynamodb:/home/dynamodblocal
        ports:
            - 8000:8000
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin:latest
        environment:
            DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
        ports:
            - 8001:8001
        depends_on:
            - dynamodb

volumes:
    dynamodb:
        driver: local
