version = 0.1
[prod.deploy.parameters]
stack_name = "fighter-circle-prod"
resolve_s3 = true
s3_prefix = "fighter-circle-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GoogleClientId=\"785409465-vhtkkf70dupl4qnr5jvgo1leoebhr5gi.apps.googleusercontent.com\" GoogleClientSecret=\"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\" Environment=\"prod\""
image_repositories = []
disable_rollback = false

[default.deploy.parameters]
stack_name = "fighter-circle-dev"
resolve_s3 = true
s3_prefix = "fighter-circle-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "GoogleClientId=\"785409465-vhtkkf70dupl4qnr5jvgo1leoebhr5gi.apps.googleusercontent.com\" GoogleClientSecret=\"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\" Environment=\"dev\""
image_repositories = []
