import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NextAuthProvider from '@/providers/NextAuth';
import { getSession } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    //
    const session = await getSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider session={session}>{children}</NextAuthProvider>
            </body>
        </html>
    );
}
